#!/bin/bash

### BEGIN INIT INFO
# Provides:          callmonitor
# Required-Start:    $all
# Required-Stop::    $all
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Start callmonitor at boot time
# Description:       Manage the callmonitor daemon, a Fritzbox callmonitor for Loxberry.
### END INIT INFO

#set -e
#set -u
#${DEBIAN_SCRIPT_DEBUG:+ set -v -x}
. /lib/lsb/init-functions
case "$1" in
        'start')
                log_daemon_msg "Starting callmonitor service" "callmonitor"
                cd REPLACELBHOMEDIR/webfrontend/htmlauth/plugins/REPLACELBPPLUGINDIR/bin
                ./callmonitor >> REPLACELBHOMEDIR/log/plugins/REPLACELBPPLUGINDIR/callmonitor.log &
                log_end_msg 0 ;;
        'stop')
                log_daemon_msg "Stopping callmonitor service" "callmonitor"
                /usr/bin/killall callmonitor &
                log_end_msg 0;;
        'restart')
                log_daemon_msg "Restarting callmonitor service" "callmonitor"
                /usr/bin/killall callmonitor &
                cd REPLACELBHOMEDIR/webfrontend/htmlauth/plugins/REPLACELBPPLUGINDIR/bin
                ./callmonitor >> REPLACELBHOMEDIR/log/plugins/REPLACELBPPLUGINDIR/callmonitor.log &
                log_end_msg 0;;
        '')
                if [ -h /etc/init.d/callmonitor ]
                then
                  /usr/sbin/service callmonitor start
                else
                  ln -s REPLACELBHOMEDIR/system/daemons/plugins/REPLACELBPPLUGINDIR /etc/init.d/callmonitor
                  /bin/systemctl daemon-reload
                  /etc/init.d/callmonitor start
                fi;;
        *)
                echo "usage $0 start|stop|restart" ;;

esac
